#!/usr/bin/env python3
"""
generate_plan.py — Generate execution plans from classified state.json

Produces:
  - For bookmarks: a new bookmark HTML file with folder structure
  - For files: a shell script that creates directories and moves files
  - For photos: a rename/move script

Usage:
  python3 generate_plan.py <state_dir> <output_dir>
"""

import json
import os
import sys
from datetime import datetime, timezone
from html import escape
from pathlib import Path


def read_state(state_dir: Path) -> dict:
    return json.loads((state_dir / "state.json").read_text(encoding="utf-8"))


def read_taxonomy(state_dir: Path) -> dict:
    return json.loads((state_dir / "taxonomy.json").read_text(encoding="utf-8"))


# ─── Bookmark Plan ────────────────────────────────────────────────────

def generate_bookmark_html(state: dict, taxonomy: dict, output_path: Path):
    """Generate a Netscape-format bookmark HTML with nested folder hierarchy.

    Uses the taxonomy parent/subcategories fields to build a proper tree:
      Top-level folders → subfolders → bookmarks
    Falls back to flat structure if no hierarchy is defined.
    """
    categories = taxonomy.get("categories", {})
    items = state.get("items", [])

    # Group items by category
    by_category: dict[str, list[dict]] = {}
    uncategorized: list[dict] = []

    for item in items:
        cls = item.get("classification")
        if cls and item.get("status") in ("classified", "user_resolved"):
            cat = cls.get("category", "")
            if cat:
                by_category.setdefault(cat, []).append(item)
            else:
                uncategorized.append(item)
        else:
            uncategorized.append(item)

    lines = [
        '<!DOCTYPE NETSCAPE-Bookmark-file-1>',
        '<!-- Generated by Bulk Organizer -->',
        '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">',
        '<TITLE>Bookmarks</TITLE>',
        '<H1>Bookmarks</H1>',
        '<DL><p>',
    ]

    def write_bookmark(item: dict, indent: int):
        pad = "    " * indent
        orig = item.get("original", {})
        url = orig.get("url", "")
        title = orig.get("title", url)
        add_date = ""
        if orig.get("date_added"):
            try:
                dt = datetime.fromisoformat(orig["date_added"])
                add_date = f' ADD_DATE="{int(dt.timestamp())}"'
            except (ValueError, OSError):
                pass
        lines.append(f'{pad}<DT><A HREF="{escape(url)}"{add_date}>{escape(title)}</A>')

    def write_folder_recursive(cat_key: str, cat_items: list[dict], indent: int):
        """Write a folder and recursively write any child folders."""
        cat_info = categories.get(cat_key, {})
        folder_name = cat_info.get("name", cat_key)
        subcats = cat_info.get("subcategories", [])
        pad = "    " * indent

        lines.append(f'{pad}<DT><H3>{escape(folder_name)}</H3>')
        lines.append(f'{pad}<DL><p>')

        # Write bookmarks that belong directly to this category
        for item in cat_items:
            write_bookmark(item, indent + 1)

        # Write child folders recursively
        for child_key in sorted(subcats, key=lambda k: -len(by_category.get(k, []))):
            child_items = by_category.pop(child_key, [])
            if child_items or categories.get(child_key, {}).get("subcategories"):
                write_folder_recursive(child_key, child_items, indent + 1)

        lines.append(f'{pad}</DL><p>')

    # ── Build hierarchy tree ──
    # Identify top-level categories (those with no parent)
    top_level = []
    children = set()
    for key, info in categories.items():
        parent = info.get("parent")
        if parent and parent in categories:
            children.add(key)
        else:
            top_level.append(key)

    # Sort top-level by item count (including children's items)
    def total_items(cat_key: str) -> int:
        count = len(by_category.get(cat_key, []))
        for child in categories.get(cat_key, {}).get("subcategories", []):
            count += len(by_category.get(child, []))
        return count

    top_level.sort(key=lambda k: -total_items(k))

    # Write top-level folders with their children
    written = set()
    for cat_key in top_level:
        cat_items = by_category.pop(cat_key, [])
        if cat_items or categories.get(cat_key, {}).get("subcategories"):
            write_folder_recursive(cat_key, cat_items, 1)
            written.add(cat_key)

    # Write any remaining categories that weren't part of the hierarchy
    remaining_cats = sorted(
        [(k, v) for k, v in by_category.items() if k not in written],
        key=lambda x: -len(x[1]),
    )
    for cat_key, cat_items in remaining_cats:
        if cat_items:
            cat_info = categories.get(cat_key, {})
            folder_name = cat_info.get("name", cat_key)
            pad = "    "
            lines.append(f'{pad}<DT><H3>{escape(folder_name)}</H3>')
            lines.append(f'{pad}<DL><p>')
            for item in cat_items:
                write_bookmark(item, 2)
            lines.append(f'{pad}</DL><p>')

    if uncategorized:
        pad = "    "
        lines.append(f'{pad}<DT><H3>Uncategorized</H3>')
        lines.append(f'{pad}<DL><p>')
        for item in uncategorized:
            write_bookmark(item, 2)
        lines.append(f'{pad}</DL><p>')

    lines.append('</DL><p>')

    output_path.write_text("\n".join(lines), encoding="utf-8")

    # Count stats
    top_count = len([k for k in top_level if k in written or by_category.get(k)])
    child_count = len(children)
    return top_count + child_count + len(remaining_cats), len(uncategorized)


# ─── Filesystem Plan ──────────────────────────────────────────────────

def generate_file_move_script(state: dict, taxonomy: dict, output_dir: Path) -> Path:
    """Generate a shell script that organizes files into categorized directories."""
    categories = taxonomy.get("categories", {})
    items = state.get("items", [])
    source_path = state.get("source_path", "")

    script_lines = [
        "#!/bin/bash",
        f"# File organizer script — generated {datetime.now().isoformat()}",
        f"# Source: {source_path}",
        f"# Total files: {len(items)}",
        "",
        'set -euo pipefail',
        "",
        f'BASE_DIR="{source_path}"',
        f'ORGANIZED_DIR="{source_path}/Organized"',
        "",
        '# Create category directories',
    ]

    # Collect all category dirs needed
    cat_dirs: set[str] = set()
    moves: list[tuple[str, str]] = []

    for item in items:
        cls = item.get("classification")
        if not cls or item.get("status") not in ("classified", "user_resolved"):
            continue

        cat_key = cls.get("category", "")
        if not cat_key:
            continue

        cat_info = categories.get(cat_key, {})
        folder_name = cat_info.get("name", cat_key).replace("/", "-")

        subcat = cls.get("subcategory", "")
        if subcat:
            sub_info = categories.get(subcat, {})
            sub_name = sub_info.get("name", subcat).replace("/", "-")
            dest_dir = f"$ORGANIZED_DIR/{folder_name}/{sub_name}"
        else:
            dest_dir = f"$ORGANIZED_DIR/{folder_name}"

        cat_dirs.add(dest_dir)
        orig = item.get("original", {})
        src_path = orig.get("path", "")
        if src_path:
            moves.append((src_path, dest_dir))

    for d in sorted(cat_dirs):
        script_lines.append(f'mkdir -p "{d}"')

    script_lines.append("")
    script_lines.append("# Move files")

    for src, dest in moves:
        script_lines.append(f'mv "{src}" "{dest}/"')

    script_lines.append("")
    script_lines.append(f'echo "Done! Organized {len(moves)} files into $ORGANIZED_DIR"')

    script_path = output_dir / "execution_plan.sh"
    script_path.write_text("\n".join(script_lines), encoding="utf-8")
    script_path.chmod(0o755)
    return script_path


# ─── Photo Rename Plan ────────────────────────────────────────────────

def generate_photo_rename_script(state: dict, taxonomy: dict, output_dir: Path) -> Path:
    """Generate a script that renames/moves photos into categorized directories."""
    items = state.get("items", [])
    categories = taxonomy.get("categories", {})

    script_lines = [
        "#!/bin/bash",
        f"# Photo organizer script — generated {datetime.now().isoformat()}",
        f"# Source: {state.get('source_path', '')}",
        "",
        'set -euo pipefail',
        "",
        f'ORGANIZED_DIR="{state.get("source_path", ".")}/Organized"',
        "",
    ]

    for item in items:
        cls = item.get("classification")
        if not cls or item.get("status") not in ("classified", "user_resolved"):
            continue

        cat_key = cls.get("category", "")
        cat_info = categories.get(cat_key, {})
        folder_name = cat_info.get("name", cat_key).replace("/", "-")

        orig = item.get("original", {})
        src_path = orig.get("path", "")
        if not src_path:
            continue

        dest_dir = f"$ORGANIZED_DIR/{folder_name}"
        script_lines.append(f'mkdir -p "{dest_dir}"')
        script_lines.append(f'cp "{src_path}" "{dest_dir}/"')

    script_lines.append("")
    script_lines.append('echo "Done! Photos organized."')

    script_path = output_dir / "execution_plan.sh"
    script_path.write_text("\n".join(script_lines), encoding="utf-8")
    script_path.chmod(0o755)
    return script_path


# ─── Structured Plan (JSON) ──────────────────────────────────────────

def generate_structured_plan(state: dict, taxonomy: dict) -> dict:
    """Generate a structured execution plan (JSON) for programmatic use."""
    categories = taxonomy.get("categories", {})
    items = state.get("items", [])
    source_type = state.get("source_type", "")

    plan = {
        "source_type": source_type,
        "source_path": state.get("source_path", ""),
        "generated_at": datetime.now(tz=timezone.utc).isoformat(),
        "total_items": len(items),
        "actions": [],
    }

    for item in items:
        cls = item.get("classification")
        if not cls or item.get("status") not in ("classified", "user_resolved"):
            continue

        orig = item.get("original", {})
        cat_key = cls.get("category", "")
        cat_info = categories.get(cat_key, {})

        action = {
            "item_id": item.get("id"),
            "source": orig.get("url", orig.get("path", "")),
            "title": orig.get("title", orig.get("name", "")),
            "destination_category": cat_info.get("name", cat_key),
            "category_key": cat_key,
            "confidence": cls.get("confidence", 0),
        }
        plan["actions"].append(action)

    return plan


# ─── Main ─────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 3:
        print("Usage: generate_plan.py <state_dir> <output_dir>", file=sys.stderr)
        sys.exit(1)

    state_dir = Path(sys.argv[1]).expanduser().resolve()
    output_dir = Path(sys.argv[2]).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    state = read_state(state_dir)
    taxonomy = read_taxonomy(state_dir)
    source_type = state.get("source_type", "")

    # Structured plan (always generated)
    plan = generate_structured_plan(state, taxonomy)
    plan_path = output_dir / "execution_plan.json"
    plan_path.write_text(json.dumps(plan, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Structured plan: {plan_path} ({len(plan['actions'])} actions)")

    # Type-specific output
    if "bookmark" in source_type:
        html_path = output_dir / "bookmarks_organized.html"
        cat_count, uncat_count = generate_bookmark_html(state, taxonomy, html_path)
        print(f"Bookmark HTML: {html_path} ({cat_count} categories, {uncat_count} uncategorized)")

    elif source_type == "filesystem":
        script_path = generate_file_move_script(state, taxonomy, output_dir)
        print(f"Move script: {script_path}")

    elif source_type == "photos":
        script_path = generate_photo_rename_script(state, taxonomy, output_dir)
        print(f"Photo script: {script_path}")

    else:
        print(f"Warning: unknown source_type '{source_type}', only JSON plan generated")


if __name__ == "__main__":
    main()
